name: main_workflow
on: push
jobs:
  linter-execution:
  runs-on: ubuntu-latest
    - name: Linter execution
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Linter execution run
      uses: github/super-linter@v3
      env:
        DEFAULT_BRANCH: nodejs_linter_job
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LINTER_RULES_PATH: /
        JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json 
        VALIDATE_JAVASCRIPT_ES: true